In [84]:
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt
import PIL 
import scipy
print(tf.__version__)

1.8.0


In [85]:
fashion_mnist = keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

In [86]:
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat', 
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

In [87]:
train_images.shape

(60000, 28, 28)

In [88]:
train_labels.shape

(60000,)

In [89]:
#train_images = train_images/255.0
#test_images = test_images/255.0

In [90]:
train_images_flat = Flatten(train_images)
test_images_flat = Flatten(test_images)

In [91]:
train_labels_1=train_labels.reshape(1,train_images.shape[0])

In [92]:
a=np.array(labelvector(train_labels_1))

In [93]:
Y=Flatten(a)

In [94]:
Y.shape

(10, 60000)

In [95]:
layer_dims=layer_dims(train_images_flat,Y)

In [96]:
layer_dims

(784, 2, 10)

In [97]:
test_labels_1=test_labels.reshape(1,test_images.shape[0])

In [98]:
Y_output=np.array(labelvector(test_labels_1))

In [99]:
Y_output_flat=Flatten(Y_output)

In [100]:
Y_output_flat.shape

(10, 10000)

In [101]:
parameters=initialize_parameters_deep(layer_dims)

In [102]:
parameters

{'W1': array([[ 0.01788628,  0.0043651 ,  0.00096497, ...,  0.02317775,
          0.00260241, -0.00010695],
        [-0.00231977, -0.00115205, -0.00272267, ..., -0.00260047,
          0.00585345,  0.00337422]]), 'b1': array([[0.],
        [0.]]), 'W2': array([[ 0.01315434, -0.01701112],
        [ 0.01193544,  0.00826354],
        [-0.0012404 ,  0.00426534],
        [ 0.00986948,  0.00311063],
        [-0.00237987,  0.00292449],
        [-0.00686514, -0.01301407],
        [-0.00865227, -0.00761064],
        [ 0.00200944,  0.00805445],
        [ 0.00256467,  0.014689  ],
        [-0.00076082, -0.00630547]]), 'b2': array([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])}

In [103]:
parameters['W2'].shape

(10, 2)

In [115]:
Z,cache=linear_forward(train_images_flat, parameters['W1'], parameters['b1'])

In [116]:
Z.shape

(2, 60000)

In [117]:
A,cache=linear_activation_forward(train_images_flat, parameters['W1'], parameters['b1'],activation='relu')

In [118]:
A.shape

(2, 60000)

In [119]:
AL,caches=linear_activation_forward(A,parameters['W2'],parameters['b2'],activation='sigmoid')

In [120]:
AL.shape

(10, 60000)

In [121]:
AL,caches=L_model_forward(train_images_flat, parameters)

# Till above the code is final. below this experimeniting for backward prop

In [123]:
AL.shape

(10, 60000)

In [128]:
c=compute_cost(AL,Y)

In [129]:
c

7.1249431725779075

In [132]:
AL

array([[0.53914099, 0.5178824 , 0.51626887, ..., 0.51567759, 0.55706379,
        0.5       ],
       [0.53552699, 0.51622662, 0.5147623 , ..., 0.51422571, 0.55181606,
        0.5       ],
       [0.49630166, 0.49831305, 0.49846537, ..., 0.49852118, 0.49459577,
        0.5       ],
       ...,
       [0.5059911 , 0.50273283, 0.50248607, ..., 0.50239565, 0.50875423,
        0.5       ],
       [0.50764627, 0.50348792, 0.50317298, ..., 0.50305758, 0.5111724 ,
        0.5       ],
       [0.49773154, 0.49896528, 0.49905871, ..., 0.49909294, 0.49668516,
        0.5       ]])

In [136]:
AL.shape

(10, 60000)

In [133]:
Y

array([[0, 1, 1, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [137]:
Y.shape

(10, 60000)

In [176]:
caches

[((array([[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
   array([[ 0.01788628,  0.0043651 ,  0.00096497, ...,  0.02317775,
            0.00260241, -0.00010695],
          [-0.00231977, -0.00115205, -0.00272267, ..., -0.00260047,
            0.00585345,  0.00337422]]),
   array([[0.],
          [0.]])),
  array([[ 11.92648304,   5.44004084,   4.94882176, ...,   4.76883946,
           17.42801583,  -7.55446924],
         [-55.44334299,  -5.7011375 , -25.72775183, ..., -19.03236416,
          -24.15690404, -23.49110436]])),
 ((array([[11.92648304,  5.44004084,  4.94882176, ...,  4.76883946,
           17.42801583,  0.        ],
          [ 0.        ,  0.        ,  0.        , ...,  0.        ,
            0.        ,  0.        ]]), array([[ 0.01315434, -0.01701112],
          [ 0.01193544,  0.00826354],
 

In [181]:
caches[0]

((array([[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
  array([[ 0.01788628,  0.0043651 ,  0.00096497, ...,  0.02317775,
           0.00260241, -0.00010695],
         [-0.00231977, -0.00115205, -0.00272267, ..., -0.00260047,
           0.00585345,  0.00337422]]),
  array([[0.],
         [0.]])),
 array([[ 11.92648304,   5.44004084,   4.94882176, ...,   4.76883946,
          17.42801583,  -7.55446924],
        [-55.44334299,  -5.7011375 , -25.72775183, ..., -19.03236416,
         -24.15690404, -23.49110436]]))

In [190]:
caches[0][0][0].shape

(784, 60000)

In [178]:
caches[1]

((array([[11.92648304,  5.44004084,  4.94882176, ...,  4.76883946,
          17.42801583,  0.        ],
         [ 0.        ,  0.        ,  0.        , ...,  0.        ,
           0.        ,  0.        ]]), array([[ 0.01315434, -0.01701112],
         [ 0.01193544,  0.00826354],
         [-0.0012404 ,  0.00426534],
         [ 0.00986948,  0.00311063],
         [-0.00237987,  0.00292449],
         [-0.00686514, -0.01301407],
         [-0.00865227, -0.00761064],
         [ 0.00200944,  0.00805445],
         [ 0.00256467,  0.014689  ],
         [-0.00076082, -0.00630547]]), array([[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.]])),
 array([[ 0.15688497,  0.07156013,  0.06509846, ...,  0.06273092,
          0.22925398,  0.        ],
        [ 0.14234783,  0.06492928,  0.05906637, ...,  0.0569182 ,
          0.20801104,  0.        ],
        [-0.01479364, -0.00674784, -0.00613853, ..., -0.00591528,

In [196]:
caches[1][0][1].shape

(10, 2)

In [164]:
grads = {}
L = len(caches) # the number of layers
m = AL.shape[1]
Y = Y.reshape(AL.shape) # after this line, Y is the same shape as AL    
dAL = dAL = - (np.divide(Y, AL) - np.divide(1 - Y, 1 - AL))

In [144]:
L

2

In [145]:
m

60000

In [146]:
Y.shape

(10, 60000)

In [147]:
dAL.shape

(10, 60000)

In [166]:
current_cache = caches[-1]
grads["dA" + str(L)], grads["dW" + str(L)], grads["db" + str(L)] = linear_backward(sigmoid_backward(dAL, 
                                                                                                        current_cache[1]), 
                                                                                       current_cache[0])

In [198]:
grads

{'dA2': array([[ 0.01222555, -0.00258466, -0.00265255, ...,  0.00060743,
         -0.00093366,  0.01668257],
        [ 0.00530847,  0.01583996,  0.0158268 , ..., -0.00429978,
          0.01616241,  0.01169714]]), 'dW2': array([[7.81770185, 0.01554167],
        [9.47265064, 0.03128531],
        [5.20299987, 0.02666471],
        [8.83226196, 0.01453312],
        [4.57921372, 0.02678164],
        [6.47691843, 0.01620188],
        [4.4364992 , 0.01821699],
        [8.32016638, 0.02949382],
        [6.19862399, 0.02506811],
        [6.79796979, 0.02578609]]), 'db2': array([0.45260446, 0.44821841, 0.39498232, 0.44001684, 0.39030319,
        0.37185771, 0.36476305, 0.4083374 , 0.41069954, 0.39679604])}

In [200]:
grads['dA2'].shape

(2, 60000)

In [201]:
for l in reversed(range(L-1)):
        # lth layer: (RELU -> LINEAR) gradients.
        # Inputs: "grads["dA" + str(l + 2)], caches". Outputs: "grads["dA" + str(l + 1)] , grads["dW" + str(l + 1)] , grads["db" + str(l + 1)] 
        
        current_cache = caches[l]
        dA_prev_temp, dW_temp, db_temp = linear_backward(relu_backward(grads["dA" + str(L)], current_cache[1]), current_cache[0])
        grads["dA" + str(l + 1)] = dA_prev_temp
        grads["dW" + str(l + 1)] = dW_temp
        grads["db" + str(l + 1)] = db_temp

In [204]:
grads=L_model_backward(AL, Y, caches)

In [205]:
grads

{'dA2': array([[0.08448824, 0.02876099, 0.02855151, ..., 0.04164412, 0.03394535,
         0.        ],
        [0.03362775, 0.10210351, 0.10211196, ..., 0.02155446, 0.10222542,
         0.        ]]), 'dW2': array([[3.33763933e+01, 2.13017871e-02],
        [3.99400215e+01, 1.29004971e-01],
        [7.76885565e-02, 8.61788148e-02],
        [3.66345204e+01, 5.95405948e-02],
        [2.13165966e-02, 6.00692683e-02],
        [0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00],
        [3.33283670e+01, 1.18560240e-01],
        [2.48515974e+01, 1.01830878e-01],
        [0.00000000e+00, 0.00000000e+00]]), 'db2': array([1.30144428, 1.51418595, 0.01274544, 1.40966505, 0.00893062,
        0.        , 0.        , 1.39060052, 1.10011788, 0.        ]), 'dA1': array([[ 1.51118080e-03,  5.14427242e-04,  5.10680405e-04, ...,
          7.44858670e-04,  6.07156210e-04,  0.00000000e+00],
        [ 3.68799511e-04,  1.25544551e-04,  1.24630146e-04, ...,
          1.81780706e-04,  1.4

In [66]:
def L_layer_model(X, Y, layers_dims, learning_rate = 0.009, num_iterations = 3000, print_cost=False):#lr was 0.009
    """
    Implements a L-layer neural network: [LINEAR->RELU]*(L-1)->LINEAR->SIGMOID.
    
    Arguments:
    X -- data, numpy array of shape (number of examples, num_px * num_px * 3)
    Y -- true "label" vector (containing 0 if cat, 1 if non-cat), of shape (1, number of examples)
    layers_dims -- list containing the input size and each layer size, of length (number of layers + 1).
    learning_rate -- learning rate of the gradient descent update rule
    num_iterations -- number of iterations of the optimization loop
    print_cost -- if True, it prints the cost every 100 steps
    
    Returns:
    parameters -- parameters learnt by the model. They can then be used to predict.
    """

    np.random.seed(1)
    costs = []                         # keep track of cost
    
    # Parameters initialization. (≈ 1 line of code)

    parameters = initialize_parameters_deep(layers_dims)
 
    
    # Loop (gradient descent)
    for i in range(0, num_iterations):

        # Forward propagation: [LINEAR -> RELU]*(L-1) -> LINEAR -> SIGMOID.

        AL, caches = L_model_forward(X, parameters)

        
        # Compute cost.

        cost = compute_cost(AL, Y)

    
        # Backward propagation.

        grads = L_model_backward(AL, Y, caches)

 
        # Update parameters.

        parameters = update_parameters(parameters, grads, learning_rate)

                
        # Print the cost every 100 training example
        if print_cost and i % 100 == 0:
            print ("Cost after iteration %i: %f" %(i, cost))
        if print_cost and i % 100 == 0:
            costs.append(cost)
            
    # plot the cost
    plt.plot(np.squeeze(costs))
    plt.ylabel('cost')
    plt.xlabel('iterations (per tens)')
    plt.title("Learning rate =" + str(learning_rate))
    plt.show()
    
    return parameters

In [67]:
def initialize_parameters_deep(layer_dims):
    """
    Arguments:
    layer_dims -- python array (list) containing the dimensions of each layer in our network
    layer_dims [2,4,1]: There are two inputs, one hidden layer with 4 hidden units, and an output layer with 1 output unit.
    Returns:
    parameters -- python dictionary containing your parameters "W1", "b1", ..., "WL", "bL":
                    Wl -- weight matrix of shape (layer_dims[l], layer_dims[l-1])
                    bl -- bias vector of shape (layer_dims[l], 1)
    """
    
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)            # number of layers in the network
    

    for l in range(1, L):
        
        parameters['W' + str(l)] = np.random.randn(layer_dims[l], layer_dims[l-1]) * 0.01
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
        
        
        assert(parameters['W' + str(l)].shape == (layer_dims[l], layer_dims[l-1]))
        assert(parameters['b' + str(l)].shape == (layer_dims[l], 1))
        
    return parameters

In [114]:
def L_model_forward(X, parameters):
    """
    Implement forward propagation for the [LINEAR->RELU]*(L-1)->LINEAR->SIGMOID computation
    
    Arguments:
    X -- data, numpy array of shape (input size, number of examples)
    parameters -- output of initialize_parameters_deep()
    
    Returns:
    AL -- last post-activation value
    caches -- list of caches containing:
                every cache of linear_activation_forward() (there are L-1 of them, indexed from 0 to L-1)
    """

    caches = []
    A = X
    L = len(parameters) // 2                  # number of layers in the neural network
    
    # Implement [LINEAR -> RELU]*(L-1). Add "cache" to the "caches" list.
    
    for l in range(1, L):
        A_prev = A 
        A, cache = linear_activation_forward(A_prev, parameters['W' + str(l)], parameters['b' + str(l)], activation='relu')
        caches.append(cache)
        
    
    # Implement LINEAR -> SIGMOID. Add "cache" to the "caches" list.
    
    AL, cache = linear_activation_forward(A, parameters['W' + str(L)], parameters['b' + str(L)], activation='sigmoid')
    caches.append(cache)
    
    
    assert(AL.shape == (10,X.shape[1]))
            
    return AL, caches

In [69]:
def linear_activation_forward(A_prev, W, b, activation):
    """
    Implement the forward propagation for the LINEAR->ACTIVATION layer

    Arguments:
    A_prev -- activations from previous layer (or input data): (size of previous layer, number of examples)
    W -- weights matrix: numpy array of shape (size of current layer, size of previous layer)
    b -- bias vector, numpy array of shape (size of the current layer, 1)
    activation -- the activation to be used in this layer, stored as a text string: "sigmoid" or "relu"

    Returns:
    A -- the output of the activation function, also called the post-activation value 
    cache -- a python dictionary containing "linear_cache" and "activation_cache";
             stored for computing the backward pass efficiently
    """
    
    if activation == "sigmoid":
        # Inputs: "A_prev, W, b". Outputs: "A, activation_cache".
        
        Z, linear_cache = linear_forward(A_prev, W, b)
        A, activation_cache = sigmoid(Z)
        
    
    elif activation == "relu":
        # Inputs: "A_prev, W, b". Outputs: "A, activation_cache".

        Z, linear_cache = linear_forward(A_prev, W, b)
        A, activation_cache = relu(Z)
        
    
    assert (A.shape == (W.shape[0], A_prev.shape[1]))
    cache = (linear_cache, activation_cache)

    return A, cache

In [70]:
def linear_forward(A, W, b):
    """
    Implement the linear part of a layer's forward propagation.

    Arguments:
    A -- activations from previous layer (or input data): (size of previous layer, number of examples)
    W -- weights matrix: numpy array of shape (size of current layer, size of previous layer)
    b -- bias vector, numpy array of shape (size of the current layer, 1)

    Returns:
    Z -- the input of the activation function, also called pre-activation parameter 
    cache -- a python dictionary containing "A", "W" and "b" ; stored for computing the backward pass efficiently
    """
    
    
    Z = np.dot(W,A)+b
    
    
    assert(Z.shape == (W.shape[0], A.shape[1]))
    cache = (A, W, b)
    
    return Z, cache

In [71]:
def compute_cost(AL, Y):
    """
    Implement the cost function defined by equation (7).

    Arguments:
    AL -- probability vector corresponding to your label predictions, shape (1, number of examples)
    Y -- true "label" vector (for example: containing 0 if non-cat, 1 if cat), shape (1, number of examples)

    Returns:
    cost -- cross-entropy cost
    """
    
    m = Y.shape[1]

    # Compute loss from aL and y.
    
    cost = (-1 / m) * np.sum(np.multiply(Y, np.log(AL)) + np.multiply(1 - Y, np.log(1 - AL)))
    
    
    cost = np.squeeze(cost)      # To make sure your cost's shape is what we expect (e.g. this turns [[17]] into 17).
    assert(cost.shape == ())
    
    return cost

In [203]:
def L_model_backward(AL, Y, caches):
    """
    Implement the backward propagation for the [LINEAR->RELU] * (L-1) -> LINEAR -> SIGMOID group
    
    Arguments:
    AL -- probability vector, output of the forward propagation (L_model_forward())
    Y -- true "label" vector (containing 0 if non-cat, 1 if cat)
    caches -- list of caches containing:
                every cache of linear_activation_forward() with "relu" (it's caches[l], for l in range(L-1) i.e l = 0...L-2)
                the cache of linear_activation_forward() with "sigmoid" (it's caches[L-1])
    
    Returns:
    grads -- A dictionary with the gradients
             grads["dA" + str(l)] = ... 
             grads["dW" + str(l)] = ...
             grads["db" + str(l)] = ... 
    """
    grads = {}
    L = len(caches) # the number of layers
    m = AL.shape[1]
    Y = Y.reshape(AL.shape) # after this line, Y is the same shape as AL
    
    # Initializing the backpropagation
    
    dAL = dAL = - (np.divide(Y, AL) - np.divide(1 - Y, 1 - AL))
    
    
    # Lth layer (SIGMOID -> LINEAR) gradients. Inputs: "AL, Y, caches". Outputs: "grads["dAL"], grads["dWL"], grads["dbL"]
    
    current_cache = caches[-1]
    grads["dA" + str(L)], grads["dW" + str(L)], grads["db" + str(L)] = linear_backward(relu_backward(dAL, 
                                                                                                        current_cache[1]), 
                                                                                       current_cache[0])
    
    
    for l in reversed(range(L-1)):
        # lth layer: (RELU -> LINEAR) gradients.
        # Inputs: "grads["dA" + str(l + 2)], caches". Outputs: "grads["dA" + str(l + 1)] , grads["dW" + str(l + 1)] , grads["db" + str(l + 1)] 
        
        current_cache = caches[l]
        dA_prev_temp, dW_temp, db_temp = linear_backward(relu_backward(grads["dA" + str(L)], current_cache[1]), current_cache[0]) # replaced dAL with grads["dA" + str(L)] because the dimensions were not matching
        grads["dA" + str(l + 1)] = dA_prev_temp
        grads["dW" + str(l + 1)] = dW_temp
        grads["db" + str(l + 1)] = db_temp
        

    return grads

In [73]:
def linear_activation_backward(dA, cache, activation):
    """
    Implement the backward propagation for the LINEAR->ACTIVATION layer.
    
    Arguments:
    dA -- post-activation gradient for current layer l 
    cache -- tuple of values (linear_cache, activation_cache) we store for computing backward propagation efficiently
    activation -- the activation to be used in this layer, stored as a text string: "sigmoid" or "relu"
    
    Returns:
    dA_prev -- Gradient of the cost with respect to the activation (of the previous layer l-1), same shape as A_prev
    dW -- Gradient of the cost with respect to W (current layer l), same shape as W
    db -- Gradient of the cost with respect to b (current layer l), same shape as b
    """
    linear_cache, activation_cache = cache
    
    if activation == "relu":
        
        dZ = relu_backward(dA, activation_cache)
        
    elif activation == "sigmoid":
        
        dZ = sigmoid_backward(dA, activation_cache)
        
    
    # Shorten the code
    dA_prev, dW, db = linear_backward(dZ, linear_cache)
    
    return dA_prev, dW, db

In [130]:
def linear_backward(dZ, cache):
    """
    Implement the linear portion of backward propagation for a single layer (layer l)

    Arguments:
    dZ -- Gradient of the cost with respect to the linear output (of current layer l)
    cache -- tuple of values (A_prev, W, b) coming from the forward propagation in the current layer

    Returns:
    dA_prev -- Gradient of the cost with respect to the activation (of the previous layer l-1), same shape as A_prev
    dW -- Gradient of the cost with respect to W (current layer l), same shape as W
    db -- Gradient of the cost with respect to b (current layer l), same shape as b
    """
    A_prev, W, b = cache
    m = A_prev.shape[1]

    
    dW = np.dot(dZ, cache[0].T) / m
    db = np.squeeze(np.sum(dZ, axis=1, keepdims=True)) / m
    dA_prev = np.dot(cache[1].T, dZ)
    
    
    assert (dA_prev.shape == A_prev.shape)
    assert (dW.shape == W.shape)
    #assert (isinstance(db, float))
    assert (db.dtype==float)  #Used this because the above assert wasn't working. once it is working properly, change this
    
    return dA_prev, dW, db

In [75]:
def relu_backward(dA, cache):
    """
    Implement the backward propagation for a single RELU unit.

    Arguments:
    dA -- post-activation gradient, of any shape
    cache -- 'Z' where we store for computing backward propagation efficiently

    Returns:
    dZ -- Gradient of the cost with respect to Z
    """
    
    Z = cache
    dZ = np.array(dA, copy=True) # just converting dz to a correct object.
    
    # When z <= 0, you should set dz to 0 as well. 
    dZ[Z <= 0] = 0
    
    assert (dZ.shape == Z.shape)
    
    return dZ

In [76]:
def sigmoid_backward(dA, cache):
    """
    Implement the backward propagation for a single SIGMOID unit.

    Arguments:
    dA -- post-activation gradient, of any shape
    cache -- 'Z' where we store for computing backward propagation efficiently

    Returns:
    dZ -- Gradient of the cost with respect to Z
    """
    
    Z = cache
    
    s = 1/(1+np.exp(-Z))
    dZ = dA * s * (1-s)
    
    assert (dZ.shape == Z.shape)
    
    return dZ

In [77]:
def relu(Z):
    """
    Implement the RELU function.

    Arguments:
    Z -- Output of the linear layer, of any shape

    Returns:
    A -- Post-activation parameter, of the same shape as Z
    cache -- a python dictionary containing "A" ; stored for computing the backward pass efficiently
    """
    
    A = np.maximum(0,Z)
    
    assert(A.shape == Z.shape)
    
    cache = Z 
    return A, cache

In [78]:
def sigmoid(Z):
    """
    Implements the sigmoid activation in numpy
    
    Arguments:
    Z -- numpy array of any shape
    
    Returns:
    A -- output of sigmoid(z), same shape as Z
    cache -- returns Z as well, useful during backpropagation
    """
    
    A = 1/(1+np.exp(-Z))
    cache = Z
    
    return A, cache

In [79]:
def layer_dims(X, Y):
    """
    Arguments:
    X -- input dataset of shape (input size, number of examples)
    Y -- labels of shape (output size, number of examples)
    
    Returns:
    n_x -- the size of the input layer
    n_h -- the size of the hidden layer
    n_y -- the size of the output layer
    """
   
    n_x = X.shape[0] # size of input layer
    n_h = 2
    n_y = Y.shape[0] # size of output layer
    
    return (n_x, n_h, n_y)

In [80]:
def predict(X, y, parameters):
    """
    This function is used to predict the results of a  L-layer neural network.
    
    Arguments:
    X -- data set of examples you would like to label
    parameters -- parameters of the trained model
    
    Returns:
    p -- predictions for the given dataset X
    """
    
    m = X.shape[1]
    n = len(parameters) // 2 # number of layers in the neural network
    p = np.zeros((1,m))
    
    # Forward propagation
    probas, caches = L_model_forward(X, parameters)

    
    # convert probas to 0/1 predictions
    for i in range(0, probas.shape[1]):
        if probas[0,i] > 0.5:
            p[0,i] = 1
        else:
            p[0,i] = 0
    
    #print results
    #print ("predictions: " + str(p))
    #print ("true labels: " + str(y))
    print("Accuracy: "  + str(np.sum((p == y)/m)))
        
    return p

In [81]:
def Flatten(X):
    return X.reshape(X.shape[0], -1).T

In [82]:
def update_parameters(parameters, grads, learning_rate):
    """
    Update parameters using gradient descent
    
    Arguments:
    parameters -- python dictionary containing your parameters 
    grads -- python dictionary containing your gradients, output of L_model_backward
    
    Returns:
    parameters -- python dictionary containing your updated parameters 
                  parameters["W" + str(l)] = ... 
                  parameters["b" + str(l)] = ...
    """
    
    L = len(parameters) // 2 # number of layers in the neural network

   
    for l in range(L):
        parameters["W" + str(l + 1)] = parameters["W" + str(l + 1)] - learning_rate * grads["dW" + str(l + 1)]
        parameters["b" + str(l + 1)] = parameters["b" + str(l + 1)] - learning_rate * grads["db" + str(l + 1)]
    
        
    return parameters

In [83]:
def labelvector(Y):
    X=[]
    l=Y.shape[1]
    for i in range (0,l):
        if Y[0,i]==0:
            n=[[1],[0],[0],[0],[0],[0],[0],[0],[0],[0]]
        elif Y[0,i]==1:
            n=[[0],[1],[0],[0],[0],[0],[0],[0],[0],[0]]
        elif Y[0,i]==2:
            n=[[0],[0],[1],[0],[0],[0],[0],[0],[0],[0]]
        elif Y[0,i]==3:
            n=[[0],[0],[0],[1],[0],[0],[0],[0],[0],[0]]
        elif Y[0,i]==4:
            n=[[0],[0],[0],[0],[1],[0],[0],[0],[0],[0]]
        elif Y[0,i]==5:
            n=[[0],[0],[0],[0],[0],[1],[0],[0],[0],[0]]
        elif Y[0,i]==6:
            n=[[0],[0],[0],[0],[0],[0],[1],[0],[0],[0]]
        elif Y[0,i]==7:
            n=[[0],[0],[0],[0],[0],[0],[0],[1],[0],[0]]
        elif Y[0,i]==8:
            n=[[0],[0],[0],[0],[0],[0],[0],[0],[1],[0]]
        elif Y[0,i]==9:
            n=[[0],[0],[0],[0],[0],[0],[0],[0],[0],[1]]
        X.append(n)
    return X